[[modules]]
id = "generator"
module = "generator.wasm"


[[modules]]
id = "doubler1"
module_path = "./doubler.wasm"


[[modules]]
id = "doubler2"
module = "./doubler.wasm"

[[modules.dependencies]]
id = "doubler1"
from_port = 0
to_port = 0


[output]
module = "doubler2"
port = 0