[generator]
module = "generator.wasm"

[doubler1]
module = "./doubler.wasm"
dependencies = [
    {
        module = {
            id = "doubler2", 
            output_port = 0,
        }, 
        input_port = 0,
    },
]

[doubler2]
module = "doubler.wasm"

[output]
module = "doubler2"
port = 0